#Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

#Array Creation: Conversion from other python structures

In [6]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray[0,1]=10

In [12]:
listarray

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

#Array Creation: Intrinsic numpy array creation objects

In [13]:
zeros=np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng=np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace=np.linspace(1,10,5) 
#gives 5 equally linearly spaces elements from 1-10 

In [18]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
emp=np.empty((4,6))

#creates an empty array of the given size whose values can be changed accordingly later

In [20]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219442e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 8.45590539e-307,
        6.23054972e-307, 1.33511562e-306, 6.89805151e-307]])

In [21]:
emp_like=np.empty_like(lspace)

#creates an empty array but similar to the array provided as the argument

In [22]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
id=np.identity(5)

#gives an indentity matrix of a given size

In [24]:
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr=np.arange(40)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [27]:
arr.reshape(2,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [28]:
arr.ravel()

#returns the same 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

#AXIS

In [29]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [30]:
arr=np.array(x)

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
arr.sum(axis=0)

array([12,  8,  9])

In [33]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [34]:
arr.T

#returns the transpose of the matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [35]:
arr.flat

#creates an iterator for the array

In [36]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [37]:
arr.ndim

#returns the number of dimensions

2

In [38]:
arr.nbytes

#no. of bytes consumed by the array


36

In [39]:
one=np.array([1,3,4,65,7])

In [40]:
one.argmax()

#returns the index at which max element is situated

3

In [41]:
one.argmin()

#returns the index at which min element is situated

0

In [42]:
one.argsort()

#arrangement of indices to sort the array

array([0, 1, 2, 4, 3], dtype=int64)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
arr2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [48]:
arr+arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [49]:
arr*arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [50]:
[34,56]+[54,36]

[34, 56, 54, 36]

In [51]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [52]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [53]:
arr.sum()

29

In [54]:
arr.max()

7

In [55]:
arr.min()

0

In [56]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [57]:
type(np.where(arr>5))

tuple

In [58]:
np.count_nonzero(arr)

8

In [59]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [60]:
import sys

In [61]:
py_arr=[1,2,3,4]

In [62]:
np_arr=np.array(py_arr)

In [63]:
sys.getsizeof(1)*len(py_arr)

112

In [65]:
np_arr.itemsize*np_arr.size

16